name: dreamic
description: "A general-purpose package for Flutter/Firebase apps."
version: 0.3.3
repository: https://github.com/dreamchrome/dreamic
issue_tracker: https://github.com/dreamchrome/dreamic/issues

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^6.1.1
  firebase_storage: ^13.0.3
  cloud_firestore: ^6.0.3
  cloud_functions: ^6.0.3
  firebase_core: ^4.2.0

  firebase_messaging: ^16.0.3
  firebase_remote_config: ^6.1.0
  firebase_crashlytics: ^5.0.3

  get_it: ^9.0.5
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  json_annotation: ^4.9.0

  exponential_back_off: ^0.1.0+2
  flutter_timezone: ^5.0.1
  dartz: ^0.10.1
  shared_preferences: ^2.5.3
  device_info_plus: ">=11.3.0 <13.0.0"  # Relaxed for livekit_client compatibility
  http: ^1.5.0
  tap_debouncer: ^2.2.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  wakelock_plus: ^1.4.0
  percent_indicator: ^4.2.5
  web: ^1.1.1
  connectivity_plus: ^6.1.5
  internet_connection_checker: ^3.0.1
  path_provider: ^2.1.5
  open_file: ^3.5.10
  flutter_local_notifications: ^18.0.1
  app_badge_plus: ^1.1.5
  adaptive_dialog: ^2.2.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.1
  json_serializable: ^6.11.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
